env:
  global:
    - CC_TEST_REPORTER_ID=9abc103facd664f32ed0b747ee1045acfb49919a2a248aadcbcaffe44724c64c
    - JRUBY_OPTS="--debug"
language: ruby
rvm:
  - jruby-9.2.12.0
jobs:
  include:
    - os: linux
      dist: xenial
      services: 
        - xvfb
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - bundle exec rspec
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
        - ruby -e "$(curl -s https://undercover-ci.com/uploader.rb)" -- --repo AndyObtiva/glimmer-dsl-swt --commit $TRAVIS_COMMIT --lcov coverage/lcov/glimmer-dsl-swt.lcov
    - os: osx
