env:
  global:
    - CC_TEST_REPORTER_ID=9abc103facd664f32ed0b747ee1045acfb49919a2a248aadcbcaffe44724c64c
    - JRUBY_OPTS="--debug"
language: ruby
rvm:
  - jruby-9.2.13.0
jobs:
  include:
    - name: JRuby Linux
      os: linux
      dist: xenial
      services: 
        - xvfb
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - bundle exec rspec
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
        - ruby -e "$(curl -s https://undercover-ci.com/uploader.rb)" -- --repo AndyObtiva/glimmer-dsl-swt --commit $TRAVIS_COMMIT --lcov coverage/lcov/glimmer-dsl-swt.lcov
    - name: JRuby Mac
      os: osx
    - name: JRuby Windows
      os: windows
      language: shell
      script:
      - export JAVA_HOME=${JAVA_HOME:-/c/jdk}
      - export PATH=${JAVA_HOME}/bin:${PATH}
      - choco install jdk8 -params 'installdir=c:\\jdk' -y
      - mkdir -p /c/jruby
      - curl -L -o /c/jruby/jruby-dist-9.2.13.0-bin.zip https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.13.0/jruby-dist-9.2.13.0-bin.zip
      - unzip /c/jruby/jruby-dist-9.2.13.0-bin.zip -d /c/jruby/
      - export PATH="/c/jruby/jruby-9.2.13.0/bin:$PATH"
      - jruby --version
      - jruby -S gem install bundler --no-document
      - jruby -S bundle
      - powershell rake
